# Generated by Django 5.2.9 on 2025-12-02 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role_alter_user_email_alter_user_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('manager', models.OneToOneField(
                    blank=True,
                    limit_choices_to={'role': 'RESTAURANT_MANAGER'},
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='restaurant',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
        ),
    ]
