# Generated by Django 5.2.9 on 2025-12-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_manageraccountrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageraccountrequest',
            name='restaurant_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_requests/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
