# Generated by Django 5.2.9 on 2025-12-18 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('card', 'Card'), ('cash_at_restaurant', 'Cash at restaurant')], max_length=30)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('pending_cash', 'Pending cash'), ('failed', 'Failed')], default='unpaid', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='accounts.reservation')),
            ],
        ),
    ]
