# Generated by Django 5.2.9 on 2025-12-18 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='reservation',
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='accounts.order'),
            preserve_default=False,
        ),
    ]
