# Generated by Django 5.2.9 on 2025-12-19 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_payment_reservation_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='accounts.order'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('new_reservation', 'New Reservation'), ('reservation_status', 'Reservation Status'), ('new_order', 'New Order'), ('order_status', 'Order Status'), ('order_edited', 'Order Edited')], max_length=50),
        ),
    ]
